// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJum3ZsBI7VjAsmTCij1_EHPEN-wwu7mU',
    appId: '1:1027251168998:web:85700bbd26808a95d3bd27',
    messagingSenderId: '1027251168998',
    projectId: 'lucidlogs-flutter',
    authDomain: 'lucidlogs-flutter.firebaseapp.com',
    storageBucket: 'lucidlogs-flutter.appspot.com',
    measurementId: 'G-C0LSEF0MDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxmEleI_lG5roPKipQ53wl4XhCbS7Zbn0',
    appId: '1:1027251168998:android:0ee894b81eca51bfd3bd27',
    messagingSenderId: '1027251168998',
    projectId: 'lucidlogs-flutter',
    storageBucket: 'lucidlogs-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcM0PbJ_bCxn5JrgngGIQW6uqntG1i-9E',
    appId: '1:1027251168998:ios:01f19cf769cf4877d3bd27',
    messagingSenderId: '1027251168998',
    projectId: 'lucidlogs-flutter',
    storageBucket: 'lucidlogs-flutter.appspot.com',
    iosBundleId: 'com.rizpur.lucidlogs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcM0PbJ_bCxn5JrgngGIQW6uqntG1i-9E',
    appId: '1:1027251168998:ios:c257b0d20d058cc9d3bd27',
    messagingSenderId: '1027251168998',
    projectId: 'lucidlogs-flutter',
    storageBucket: 'lucidlogs-flutter.appspot.com',
    iosBundleId: 'com.rizpur.lucidlogs.RunnerTests',
  );
}
